apiVersion: v1
data:
  ENCRYPT_PASSPHRASE:
  GITHUB_TOKEN:
  MANAGEMENT_TOKEN:
  MONITORING_TOKEN:
  app-privatekey.pem:
  bot-privatekey.pem:
  connect-privatekey.pem:
kind: Secret
metadata:
  name: wdk-studio-keys
type: Opaque
