# WDK configuration
wdk:
  workflows:
    path: ./workflows
  properties:
    monitoring-token: token # The default value is an empty String

# BDK configuration for local development
bdk:
  host: develop.symphony.com
  app:
    appId: appsoufiane
    privateKey:
      path: /Users/yinan.liu/Projects/certs/appSoufianneprivatekey.pem
  bot:
    username: wdkbot
    privateKey:
      path: /Users/yinan.liu/Projects/certs/privatekey.pem

logging:
  level:
    org.camunda.bpm.engine.bpmn.parser: DEBUG
    org.camunda.bpm.engine.bpmn.behavior: DEBUG
    org.camunda.bpm.engine.dmn: DEBUG
    org.camunda.bpm.engine.pvm: DEBUG
    org.camunda.bpm.dmn.feel: DEBUG
    org.camunda.bpm.engine.script: DEBUG
    com.symphony.bdk.workflow.engine.camunda.bpmn.CamundaBpmnBuilder: DEBUG
