# BDK configuration for local development
bdk:
  host: XXX
  bot:
    username: XXX
    privateKey:
      path: XXX

logging:
  level:
    org.camunda.bpm.engine.bpmn.parser: DEBUG
    org.camunda.bpm.engine.bpmn.behavior: DEBUG
    org.camunda.bpm.engine.dmn: DEBUG
    org.camunda.bpm.engine.pvm: DEBUG
    org.camunda.bpm.dmn.feel: DEBUG
    org.camunda.bpm.engine.script: DEBUG
