# WDK configuration
wdk:
  workflows:
    path:
  properties:
    management-token: ${wdk.management.token:token} # The default value is an empty String

# Spring boot configuration
spring:
  datasource:
    wdk:
      username: sa
      password: sa
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:wdk_workflow;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
