apiVersion: v1
kind: Service
metadata:
  labels:
    app: wdk-test
  name: wdk-test
spec:
  #type: NodePort
  type: LoadBalancer
  selector:
    app: wdk-test
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ports:
    - name: wdk
      port: 8080
      protocol: TCP
      targetPort: 8080
