name: Publish to Maven Central
on:
  push:
    branches:
      - master
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 11
      - name: Configure signing
        run: |
          printf "$GPG_KEY_BASE64" | base64 --decode > secring.gpg
        env:
          GPG_KEY_BASE64: ${{ secrets.GPG_KEY_BASE64 }}
      - uses: gradle/gradle-build-action@v1
        with:
          arguments: publish -PmavenRepoUsername=${{ secrets.MAVEN_USERNAME }} -PmavenRepoPassword=${{ secrets.MAVEN_PASSWORD }} -Psigning.keyId=${{ secrets.GPG_KEY_ID }} -Psigning.secretKeyRingFile=${{ github.workspace }}/secring.gpg -Psigning.password=${{ secrets.GPG_KEY_PASSPHRASE }}
